### ISSUE TITLE
Build the Tutorial epic

### ISSUE THREAD

**Issue by hosovsky** [hosovsky/uCat#2]
# As a locked-in patient, I want to be guided on the use of the speech prosthesis, so that I can gain the skill to join the metaverse and communicate digitally.

### To achieve this, a well-designed tutorial must be implemented, such that the user can:
- Configure the prosthesis without guidance from the researcher, such that individual variations in ECoG data retrieval are optimized for
- Improve over time, via progressing through levels training
- Visualize and understand their performance
- Learn to control any user interface using speech commands

---------

### The tutorial must follow best practices in task set up for human speech decoding experiments. The VR tutorial is inspired by the [Chang Lab at UCSF](https://changlab.ucsf.edu/our-team), for their[ leading speech decoding ECoG BCI solution, implanted over the ventral sensorymotor cortex](https://www.nejm.org/doi/10.1056/NEJMoa2027540).

Detailed description of the tasks our VR tutorial is generalizing can be found attached.

ECoG implants offer competitively best results for integrating Locked-in Syndrome, or other speech-paralyzed, patients back into society due to them:
- Being Safer and less damaging to implant than depth electrodes
- Being Longer-lasting than depth electrodes
- Having significantly lower noise to signal ratio than surface EEG

Alternative approaches involving endovascular or depth electrode may be considered in the future, should their 

---------

## **ACCEPTANCE CRITERIA**
- [x] create a high-fidelity dialogue map for the training program
- [x] mockup the UI with best practices
- [x] design a 'teacher' AI avatar, alongside their sounds and expressions
- [ ] code the tutorial sequence, alongside character & environemtn animation
- [ ] code the UI logic
- [ ] stress test edge cases and provide exception handling
- [ ] push to github
