### ISSUE TITLE
Create the Environment epic

### ISSUE THREAD

**Issue by hosovsky** [hosovsky/uCat#3]
# As a locked-in patient, I want to be in a minimalistic virtual environment while learning to use the prosthesis, so that I feel comfortable, focused and immersed.

---------

### The uCat style guide revolves around the main character - uCat. Attached are early sketches of the character.

However, following an agile approach the project will temporarily substitute as much propriatery digital art for open source alternatives as possible - so that the MVP can be faster to market. The temporary assets include:
- [Jammo](https://assetstore.unity.com/packages/3d/characters/jammo-character-mix-and-jam-158456#description) who replaces uCat in the MVP. Jammo's model is textured, rigged, animated, scripted and well documented - ready to be used in Unity immediately. Also includes 
- ![Cyberpunk Environment](https://user-images.githubusercontent.com/23667589/185808706-54023931-2fad-4f6c-a17f-d85fd011a70c.jpg). The kit comes with individual asset models which all have materials and textures.

---------

## **ACCEPTANCE CRITERIA**
- [ ] create a draft scene in Unity
- [ ] review by Art Director
- [ ] push to github
